### ISSUE TITLE
Plotting error due to no cartopy projection

### ISSUE THREAD

**Issue by corinnebosley** [SciTools/cube_browser#106]
The Iris sample data files atlantic_profiles and hybrid_height produce the following error when you try and plot them in the Cube Explorer:

None-type object has no attribute 'as_cartopy_projection'

**Comment by dkillick** [comment]
This is happening because the horizontal coordinates in these sample datasets have no coordinate system associated with them. This means that when you call `as_cartopy_projection` it tries to get the projection from the horizontal coordinates (which will be `None`), so it returns that error. 

Looking at the code for [`iris.plot.default_projection`](https://github.com/SciTools/iris/blob/48bb9e672fe1322ef6e87d7f998286f3b25107d7/lib/iris/plot.py#L739-L752) I think you could avoid this by using `default_projection` rather than `as_cartopy_projection` in this instance.
